export const KANGXI_RADICALS = [
  { char: "一", pinyin: "yī", meaning: "Nhất (Số một)", strokes: 1 },
  { char: "丨", pinyin: "gǔn", meaning: "Cổn (Nét sổ)", strokes: 1 },
  { char: "丶", pinyin: "zhǔ", meaning: "Chủ (Điểm, chấm)", strokes: 1 },
  { char: "丿", pinyin: "piě", meaning: "Phiệt (Nét phẩy)", strokes: 1 },
  { char: "乙", pinyin: "yǐ", meaning: "Ất (Can ất)", strokes: 1 },
  { char: "亅", pinyin: "jué", meaning: "Quyết (Nét sổ móc)", strokes: 1 },
  { char: "二", pinyin: "èr", meaning: "Nhị (Số hai)", strokes: 2 },
  { char: "亠", pinyin: "tóu", meaning: "Đầu (Không có nghĩa)", strokes: 2 },
  { char: "人", pinyin: "rén", meaning: "Nhân (Người)", strokes: 2 },
  { char: "儿", pinyin: "ér", meaning: "Nhi (Trẻ con)", strokes: 2 },
  { char: "入", pinyin: "rù", meaning: "Nhập (Vào)", strokes: 2 },
  { char: "八", pinyin: "bā", meaning: "Bát (Số tám)", strokes: 2 },
  { char: "冂", pinyin: "jiōng", meaning: "Quynh (Vùng biên giới)", strokes: 2 },
  { char: "冖", pinyin: "mì", meaning: "Mịch (Trùm khăn lên)", strokes: 2 },
  { char: "冫", pinyin: "bīng", meaning: "Băng (Nước đá)", strokes: 2 },
  { char: "几", pinyin: "jī", meaning: "Kỷ (Cái ghế)", strokes: 2 },
  { char: "凵", pinyin: "kǎn", meaning: "Khảm (Há miệng)", strokes: 2 },
  { char: "刀", pinyin: "dāo", meaning: "Đao (Con dao)", strokes: 2 },
  { char: "力", pinyin: "lì", meaning: "Lực (Sức mạnh)", strokes: 2 },
  { char: "勹", pinyin: "bāo", meaning: "Bao (Bao bọc)", strokes: 2 },
  { char: "匕", pinyin: "bǐ", meaning: "Chủy (Cái thìa)", strokes: 2 },
  { char: "匚", pinyin: "fāng", meaning: "Phương (Cái hộp)", strokes: 2 },
  { char: "匸", pinyin: "xǐ", meaning: "Hệ (Che đậy)", strokes: 2 },
  { char: "十", pinyin: "shí", meaning: "Thập (Số mười)", strokes: 2 },
  { char: "卜", pinyin: "bǔ", meaning: "Bốc (Xem bói)", strokes: 2 },
  { char: "卩", pinyin: "jié", meaning: "Tiết (Đốt tre)", strokes: 2 },
  { char: "厂", pinyin: "hǎn", meaning: "Hán (Sườn núi)", strokes: 2 },
  { char: "厶", pinyin: "sī", meaning: "Khư (Riêng tư)", strokes: 2 },
  { char: "又", pinyin: "yòu", meaning: "Hựu (Lại nữa)", strokes: 2 },
  { char: "口", pinyin: "kǒu", meaning: "Khẩu (Cái miệng)", strokes: 3 },
  { char: "囗", pinyin: "wéi", meaning: "Vi (Bao quanh)", strokes: 3 },
  { char: "土", pinyin: "tǔ", meaning: "Thổ (Đất)", strokes: 3 },
  { char: "士", pinyin: "shì", meaning: "Sĩ (Kẻ sĩ)", strokes: 3 },
  { char: "夂", pinyin: "zhǐ", meaning: "Chỉ (Đi sau)", strokes: 3 },
  { char: "夊", pinyin: "suī", meaning: "Tuy (Đi chậm)", strokes: 3 },
  { char: "夕", pinyin: "xī", meaning: "Tịch (Buổi tối)", strokes: 3 },
  { char: "大", pinyin: "dà", meaning: "Đại (To lớn)", strokes: 3 },
  { char: "女", pinyin: "nǚ", meaning: "Nữ (Phụ nữ)", strokes: 3 },
  { char: "子", pinyin: "zǐ", meaning: "Tử (Con cái)", strokes: 3 },
  { char: "宀", pinyin: "mián", meaning: "Miên (Mái nhà)", strokes: 3 },
  { char: "寸", pinyin: "cùn", meaning: "Thốn (Tấc)", strokes: 3 },
  { char: "小", pinyin: "xiǎo", meaning: "Tiểu (Nhỏ bé)", strokes: 3 },
  { char: "尢", pinyin: "wāng", meaning: "Uông (Khập khiễng)", strokes: 3 },
  { char: "尸", pinyin: "shī", meaning: "Thi (Thi thể)", strokes: 3 },
  { char: "屮", pinyin: "chè", meaning: "Triệt (Mầm non)", strokes: 3 },
  { char: "山", pinyin: "shān", meaning: "Sơn (Ngọn núi)", strokes: 3 },
  { char: "巛", pinyin: "chuān", meaning: "Xuyên (Sông ngòi)", strokes: 3 },
  { char: "工", pinyin: "gōng", meaning: "Công (Công việc)", strokes: 3 },
  { char: "己", pinyin: "jǐ", meaning: "Kỷ (Bản thân)", strokes: 3 },
  { char: "巾", pinyin: "jīn", meaning: "Cân (Cái khăn)", strokes: 3 },
  { char: "干", pinyin: "gān", meaning: "Can (Can phạm)", strokes: 3 },
  { char: "幺", pinyin: "yāo", meaning: "Yêu (Nhỏ bé)", strokes: 3 },
  { char: "广", pinyin: "yǎn", meaning: "Nghiễm (Mái nhà to)", strokes: 3 },
  { char: "廴", pinyin: "yǐn", meaning: "Dẫn (Bước dài)", strokes: 3 },
  { char: "廾", pinyin: "gǒng", meaning: "Củng (Chắp tay)", strokes: 3 },
  { char: "弋", pinyin: "yì", meaning: "Dặc (Bắn mũi tên)", strokes: 3 },
  { char: "弓", pinyin: "gōng", meaning: "Cung (Cây cung)", strokes: 3 },
  { char: "彐", pinyin: "jì", meaning: "Ký (Đầu con nhím)", strokes: 3 },
  { char: "彡", pinyin: "shān", meaning: "Sam (Lông tóc)", strokes: 3 },
  { char: "彳", pinyin: "chì", meaning: "Xích (Bước ngắn)", strokes: 3 },
  { char: "心", pinyin: "xīn", meaning: "Tâm (Trái tim)", strokes: 4 },
  { char: "戈", pinyin: "gē", meaning: "Qua (Cái giáo)", strokes: 4 },
  { char: "户", pinyin: "hù", meaning: "Hộ (Cửa một cánh)", strokes: 4 },
  { char: "手", pinyin: "shǒu", meaning: "Thủ (Bàn tay)", strokes: 4 },
  { char: "支", pinyin: "zhī", meaning: "Chi (Cành nhánh)", strokes: 4 },
  { char: "攴", pinyin: "pū", meaning: "Phộc (Đánh nhẹ)", strokes: 4 },
  { char: "文", pinyin: "wén", meaning: "Văn (Văn vẻ)", strokes: 4 },
  { char: "斗", pinyin: "dǒu", meaning: "Đẩu (Cái đấu)", strokes: 4 },
  { char: "斤", pinyin: "jīn", meaning: "Cân (Cái búa)", strokes: 4 },
  { char: "方", pinyin: "fāng", meaning: "Phương (Vuông)", strokes: 4 },
  { char: "无", pinyin: "wú", meaning: "Vô (Không có)", strokes: 4 },
  { char: "日", pinyin: "rì", meaning: "Nhật (Mặt trời)", strokes: 4 },
  { char: "曰", pinyin: "yuē", meaning: "Viết (Nói rằng)", strokes: 4 },
  { char: "月", pinyin: "yuè", meaning: "Nguyệt (Mặt trăng)", strokes: 4 },
  { char: "木", pinyin: "mù", meaning: "Mộc (Gỗ, cây)", strokes: 4 },
  { char: "欠", pinyin: "qiàn", meaning: "Khiếm (Thiếu thốn)", strokes: 4 },
  { char: "止", pinyin: "zhǐ", meaning: "Chỉ (Dừng lại)", strokes: 4 },
  { char: "歹", pinyin: "dǎi", meaning: "Đãi (Xấu xa)", strokes: 4 },
  { char: "殳", pinyin: "shū", meaning: "Thù (Binh khí)", strokes: 4 },
  { char: "毋", pinyin: "wú", meaning: "Vô (Chớ, đừng)", strokes: 4 },
  { char: "比", pinyin: "bǐ", meaning: "Tỷ (So sánh)", strokes: 4 },
  { char: "毛", pinyin: "máo", meaning: "Mao (Lông)", strokes: 4 },
  { char: "氏", pinyin: "shì", meaning: "Thị (Họ)", strokes: 4 },
  { char: "气", pinyin: "qì", meaning: "Khí (Hơi, khí)", strokes: 4 },
  { char: "水", pinyin: "shuǐ", meaning: "Thủy (Nước)", strokes: 4 },
  { char: "火", pinyin: "huǒ", meaning: "Hỏa (Lửa)", strokes: 4 },
  { char: "爪", pinyin: "zhǎo", meaning: "Trảo (Móng vuốt)", strokes: 4 },
  { char: "父", pinyin: "fù", meaning: "Phụ (Cha)", strokes: 4 },
  { char: "爻", pinyin: "yáo", meaning: "Hào (Hào trong quẻ)", strokes: 4 },
  { char: "爿", pinyin: "qiáng", meaning: "Tường (Mảnh gỗ)", strokes: 4 },
  { char: "片", pinyin: "piàn", meaning: "Phiến (Mảnh, tấm)", strokes: 4 },
  { char: "牙", pinyin: "yá", meaning: "Nha (Răng)", strokes: 4 },
  { char: "牛", pinyin: "niú", meaning: "Ngưu (Con bò)", strokes: 4 },
  { char: "犬", pinyin: "quǎn", meaning: "Khuyển (Con chó)", strokes: 4 },
  { char: "玄", pinyin: "xuán", meaning: "Huyền (Màu đen)", strokes: 5 },
  { char: "玉", pinyin: "yù", meaning: "Ngọc (Đá quý)", strokes: 5 },
  { char: "瓜", pinyin: "guā", meaning: "Qua (Quả dưa)", strokes: 5 },
  { char: "瓦", pinyin: "wǎ", meaning: "Ngõa (Ngói)", strokes: 5 },
  { char: "甘", pinyin: "gān", meaning: "Cam (Ngọt)", strokes: 5 },
  { char: "生", pinyin: "shēng", meaning: "Sinh (Sinh đẻ)", strokes: 5 },
  { char: "用", pinyin: "yòng", meaning: "Dụng (Sử dụng)", strokes: 5 },
  { char: "田", pinyin: "tián", meaning: "Điền (Ruộng)", strokes: 5 },
  { char: "疋", pinyin: "pǐ", meaning: "Thất (Cuộn vải)", strokes: 5 },
  { char: "疒", pinyin: "nè", meaning: "Nạch (Bệnh tật)", strokes: 5 },
  { char: "癶", pinyin: "bō", meaning: "Bát (Gạt chân)", strokes: 5 },
  { char: "白", pinyin: "bái", meaning: "Bạch (Màu trắng)", strokes: 5 },
  { char: "皮", pinyin: "pí", meaning: "Bì (Da)", strokes: 5 },
  { char: "皿", pinyin: "mǐn", meaning: "Mãnh (Bát đĩa)", strokes: 5 },
  { char: "目", pinyin: "mù", meaning: "Mục (Con mắt)", strokes: 5 },
  { char: "矛", pinyin: "máo", meaning: "Mâu (Cái giáo)", strokes: 5 },
  { char: "矢", pinyin: "shǐ", meaning: "Thỉ (Mũi tên)", strokes: 5 },
  { char: "石", pinyin: "shí", meaning: "Thạch (Đá)", strokes: 5 },
  { char: "示", pinyin: "shì", meaning: "Thị (Chỉ thị)", strokes: 5 },
  { char: "禸", pinyin: "róu", meaning: "Nhựu (Vết chân)", strokes: 5 },
  { char: "禾", pinyin: "hé", meaning: "Hòa (Cây lúa)", strokes: 5 },
  { char: "穴", pinyin: "xué", meaning: "Huyệt (Cái hang)", strokes: 5 },
  { char: "立", pinyin: "lì", meaning: "Lập (Đứng)", strokes: 5 },
  { char: "竹", pinyin: "zhú", meaning: "Trúc (Cây tre)", strokes: 6 },
  { char: "米", pinyin: "mǐ", meaning: "Mễ (Gạo)", strokes: 6 },
  { char: "糸", pinyin: "mì", meaning: "Mịch (Sợi tơ)", strokes: 6 },
  { char: "缶", pinyin: "fǒu", meaning: "Phẫu (Đồ gốm)", strokes: 6 },
  { char: "网", pinyin: "wǎng", meaning: "Võng (Cái lưới)", strokes: 6 },
  { char: "羊", pinyin: "yáng", meaning: "Dương (Con dê)", strokes: 6 },
  { char: "羽", pinyin: "yǔ", meaning: "Vũ (Lông chim)", strokes: 6 },
  { char: "老", pinyin: "lǎo", meaning: "Lão (Già)", strokes: 6 },
  { char: "而", pinyin: "ér", meaning: "Nhi (Và, mà)", strokes: 6 },
  { char: "耒", pinyin: "lěi", meaning: "Lỗi (Cái cày)", strokes: 6 },
  { char: "耳", pinyin: "ěr", meaning: "Nhĩ (Cái tai)", strokes: 6 },
  { char: "聿", pinyin: "yù", meaning: "Duật (Cái bút)", strokes: 6 },
  { char: "肉", pinyin: "ròu", meaning: "Nhục (Thịt)", strokes: 6 },
  { char: "臣", pinyin: "chén", meaning: "Thần (Bầy tôi)", strokes: 6 },
  { char: "自", pinyin: "zì", meaning: "Tự (Bản thân)", strokes: 6 },
  { char: "至", pinyin: "zhì", meaning: "Chí (Đến)", strokes: 6 },
  { char: "臼", pinyin: "jiù", meaning: "Cữu (Cái cối)", strokes: 6 },
  { char: "舌", pinyin: "shé", meaning: "Thiệt (Cái lưỡi)", strokes: 6 },
  { char: "舛", pinyin: "chuǎn", meaning: "Suyễn (Sai suyễn)", strokes: 6 },
  { char: "舟", pinyin: "zhōu", meaning: "Chu (Cái thuyền)", strokes: 6 },
  { char: "艮", pinyin: "gèn", meaning: "Cấn (Quẻ Cấn)", strokes: 6 },
  { char: "色", pinyin: "sè", meaning: "Sắc (Màu sắc)", strokes: 6 },
  { char: "艸", pinyin: "cǎo", meaning: "Thảo (Cây cỏ)", strokes: 6 },
  { char: "虍", pinyin: "hū", meaning: "Hô (Vằn hổ)", strokes: 6 },
  { char: "虫", pinyin: "chóng", meaning: "Trùng (Côn trùng)", strokes: 6 },
  { char: "血", pinyin: "xuè", meaning: "Huyết (Máu)", strokes: 6 },
  { char: "行", pinyin: "xíng", meaning: "Hành (Đi lại)", strokes: 6 },
  { char: "衣", pinyin: "yī", meaning: "Y (Áo)", strokes: 6 },
  { char: "襾", pinyin: "yà", meaning: "Á (Che đậy)", strokes: 6 },
  { char: "见", pinyin: "jiàn", meaning: "Kiến (Nhìn thấy)", strokes: 7 },
  { char: "角", pinyin: "jiǎo", meaning: "Giác (Cái sừng)", strokes: 7 },
  { char: "言", pinyin: "yán", meaning: "Ngôn (Lời nói)", strokes: 7 },
  { char: "谷", pinyin: "gǔ", meaning: "Cốc (Khe núi)", strokes: 7 },
  { char: "豆", pinyin: "dòu", meaning: "Đậu (Hạt đậu)", strokes: 7 },
  { char: "豕", pinyin: "shǐ", meaning: "Thỉ (Con lợn)", strokes: 7 },
  { char: "豸", pinyin: "zhì", meaning: "Trãi (Thú không sừng)", strokes: 7 },
  { char: "贝", pinyin: "bèi", meaning: "Bối (Vỏ sò)", strokes: 7 },
  { char: "赤", pinyin: "chì", meaning: "Xích (Màu đỏ)", strokes: 7 },
  { char: "走", pinyin: "zǒu", meaning: "Tẩu (Đi, chạy)", strokes: 7 },
  { char: "足", pinyin: "zú", meaning: "Túc (Cái chân)", strokes: 7 },
  { char: "身", pinyin: "shēn", meaning: "Thân (Cơ thể)", strokes: 7 },
  { char: "车", pinyin: "chē", meaning: "Xa (Xe cộ)", strokes: 7 },
  { char: "辛", pinyin: "xīn", meaning: "Tân (Cay đắng)", strokes: 7 },
  { char: "辰", pinyin: "chén", meaning: "Thần (Thời gian)", strokes: 7 },
  { char: "辵", pinyin: "chuò", meaning: "Sước (Chợt đi chợt dừng)", strokes: 7 },
  { char: "邑", pinyin: "yì", meaning: "Ấp (Thành thị)", strokes: 7 },
  { char: "酉", pinyin: "yǒu", meaning: "Dậu (Giờ Dậu)", strokes: 7 },
  { char: "采", pinyin: "cǎi", meaning: "Biện (Phân biệt)", strokes: 7 },
  { char: "里", pinyin: "lǐ", meaning: "Lý (Dặm)", strokes: 7 },
  { char: "金", pinyin: "jīn", meaning: "Kim (Kim loại)", strokes: 8 },
  { char: "长", pinyin: "cháng", meaning: "Trường (Dài, lớn)", strokes: 8 },
  { char: "门", pinyin: "mén", meaning: "Môn (Cái cửa)", strokes: 8 },
  { char: "阜", pinyin: "fù", meaning: "Phụ (Gò đất)", strokes: 8 },
  { char: "隶", pinyin: "lì", meaning: "Đãi (Kịp đến)", strokes: 8 },
  { char: "隹", pinyin: "zhuī", meaning: "Chuy (Chim đuôi ngắn)", strokes: 8 },
  { char: "雨", pinyin: "yǔ", meaning: "Vũ (Mưa)", strokes: 8 },
  { char: "青", pinyin: "qīng", meaning: "Thanh (Màu xanh)", strokes: 8 },
  { char: "非", pinyin: "fēi", meaning: "Phi (Không đúng)", strokes: 8 },
  { char: "面", pinyin: "miàn", meaning: "Diện (Khuôn mặt)", strokes: 9 },
  { char: "革", pinyin: "gé", meaning: "Cách (Da thú)", strokes: 9 },
  { char: "韦", pinyin: "wéi", meaning: "Vi (Da đã thuộc)", strokes: 9 },
  { char: "韭", pinyin: "jiǔ", meaning: "Cửu (Rau hẹ)", strokes: 9 },
  { char: "音", pinyin: "yīn", meaning: "Âm (Âm thanh)", strokes: 9 },
  { char: "页", pinyin: "yè", meaning: "Hiệt (Trang giấy)", strokes: 9 },
  { char: "风", pinyin: "fēng", meaning: "Phong (Gió)", strokes: 9 },
  { char: "飞", pinyin: "fēi", meaning: "Phi (Bay)", strokes: 9 },
  { char: "食", pinyin: "shí", meaning: "Thực (Ăn uống)", strokes: 9 },
  { char: "首", pinyin: "shǒu", meaning: "Thủ (Cái đầu)", strokes: 9 },
  { char: "香", pinyin: "xiāng", meaning: "Hương (Mùi thơm)", strokes: 9 },
  { char: "马", pinyin: "mǎ", meaning: "Mã (Con ngựa)", strokes: 10 },
  { char: "骨", pinyin: "gǔ", meaning: "Cốt (Xương)", strokes: 10 },
  { char: "高", pinyin: "gāo", meaning: "Cao (Cao lớn)", strokes: 10 },
  { char: "髟", pinyin: "biāo", meaning: "Tiêu (Tóc dài)", strokes: 10 },
  { char: "斗", pinyin: "dòu", meaning: "Đấu (Chiến đấu)", strokes: 10 },
  { char: "鬯", pinyin: "chàng", meaning: "Sưởng (Rượu cúng)", strokes: 10 },
  { char: "鬲", pinyin: "lì", meaning: "Cách (Cái đỉnh)", strokes: 10 },
  { char: "鬼", pinyin: "guǐ", meaning: "Quỷ (Ma quỷ)", strokes: 10 },
  { char: "鱼", pinyin: "yú", meaning: "Ngư (Con cá)", strokes: 11 },
  { char: "鸟", pinyin: "niǎo", meaning: "Điểu (Con chim)", strokes: 11 },
  { char: "卤", pinyin: "lǔ", meaning: "Lỗ (Đất mặn)", strokes: 11 },
  { char: "鹿", pinyin: "lù", meaning: "Lộc (Con hươu)", strokes: 11 },
  { char: "麦", pinyin: "mài", meaning: "Mạch (Lúa mạch)", strokes: 11 },
  { char: "麻", pinyin: "má", meaning: "Ma (Cây gai)", strokes: 11 },
  { char: "黄", pinyin: "huáng", meaning: "Hoàng (Màu vàng)", strokes: 12 },
  { char: "黍", pinyin: "shǔ", meaning: "Thử (Cây nếp)", strokes: 12 },
  { char: "黑", pinyin: "hēi", meaning: "Hắc (Màu đen)", strokes: 12 },
  { char: "黹", pinyin: "zhǐ", meaning: "Chỉ (May vá)", strokes: 12 },
  { char: "黾", pinyin: "mǐn", meaning: "Mãnh (Con ếch)", strokes: 13 },
  { char: "鼎", pinyin: "dǐng", meaning: "Đỉnh (Cái vạc)", strokes: 13 },
  { char: "鼓", pinyin: "gǔ", meaning: "Cổ (Cái trống)", strokes: 13 },
  { char: "鼠", pinyin: "shǔ", meaning: "Thử (Con chuột)", strokes: 13 },
  { char: "鼻", pinyin: "bí", meaning: "Tỵ (Cái mũi)", strokes: 14 },
  { char: "齐", pinyin: "qí", meaning: "Tề (Bằng phẳng)", strokes: 14 },
  { char: "齿", pinyin: "chǐ", meaning: "Xỉ (Răng)", strokes: 15 },
  { char: "龙", pinyin: "lóng", meaning: "Long (Con rồng)", strokes: 16 },
  { char: "龟", pinyin: "guī", meaning: "Quy (Con rùa)", strokes: 16 },
  { char: "龠", pinyin: "yuè", meaning: "Dược (Ống sáo)", strokes: 17 }
];

export const PINYIN_INITIALS = ['b', 'p', 'm', 'f', 'd', 't', 'n', 'l', 'g', 'k', 'h', 'j', 'q', 'x', 'zh', 'ch', 'sh', 'r', 'z', 'c', 's', 'y', 'w'];
export const PINYIN_FINALS = ['a', 'o', 'e', 'i', 'u', 'ü', 'ai', 'ei', 'ui', 'ao', 'ou', 'iu', 'ie', 'üe', 'er', 'an', 'en', 'in', 'un', 'ün', 'ang', 'eng', 'ing', 'ong'];

// Simplified mapping of valid combinations
export const VALID_PINYIN_SYLLABLES = new Set([
  "ba", "bo", "bai", "bei", "bao", "ban", "ben", "bang", "beng", "bi", "bie", "biao", "bian", "bin", "bing", "bu",
  "pa", "po", "pai", "pei", "pao", "pou", "pan", "pen", "pang", "peng", "pi", "pie", "piao", "pian", "pin", "ping", "pu",
  "ma", "mo", "me", "mai", "mei", "mao", "mou", "man", "men", "mang", "meng", "mi", "mie", "miao", "miu", "mian", "min", "ming", "mu",
  "fa", "fo", "fei", "fou", "fan", "fen", "fang", "feng", "fu",
  "da", "de", "dai", "dei", "dao", "dou", "dan", "den", "dang", "deng", "dong", "di", "die", "diao", "diu", "dian", "ding", "du", "duo", "dui", "duan", "dun",
  "ta", "te", "tai", "tao", "tou", "tan", "tang", "teng", "tong", "ti", "tie", "tiao", "tian", "ting", "tu", "tuo", "tui", "tuan", "tun",
  "na", "ne", "nai", "nei", "nao", "nou", "nan", "nen", "nang", "neng", "nong", "ni", "nie", "niao", "niu", "nian", "nin", "niang", "ning", "nu", "nuo", "nuan", "nü", "nüe",
  "la", "le", "lai", "lei", "lao", "lou", "lan", "lang", "leng", "long", "li", "lia", "lie", "liao", "liu", "lian", "lin", "liang", "ling", "lu", "luo", "luan", "lun", "lü", "lüe",
  "ga", "ge", "gai", "gei", "gao", "gou", "gan", "gen", "gang", "geng", "gong", "gu", "gua", "guo", "guai", "gui", "guan", "gun", "guang",
  "ka", "ke", "kai", "kao", "kou", "kan", "ken", "kang", "keng", "kong", "ku", "kua", "kuo", "kuai", "kui", "kuan", "kun", "kuang",
  "ha", "he", "hai", "hei", "hao", "hou", "han", "hen", "hang", "heng", "hong", "hu", "hua", "huo", "huai", "hui", "huan", "hun", "huang",
  "ji", "jia", "jie", "jiao", "jiu", "jian", "jin", "jiang", "jing", "jiong", "ju", "jue", "juan", "jun",
  "qi", "qia", "qie", "qiao", "qiu", "qian", "qin", "qiang", "qing", "qiong", "qu", "que", "quan", "qun",
  "xi", "xia", "xie", "xiao", "xiu", "xian", "xin", "xiang", "xing", "xiong", "xu", "xue", "xuan", "xun",
  "zha", "zhe", "zhi", "zhai", "zhao", "zhou", "zhan", "zhen", "zhang", "zheng", "zhong", "zhu", "zhua", "zhuo", "zhuai", "zhui", "zhuan", "zhun", "zhuang",
  "cha", "che", "chi", "chai", "chao", "chou", "chan", "chen", "chang", "cheng", "chong", "chu", "chua", "chuo", "chuai", "chui", "chuan", "chun", "chuang",
  "sha", "she", "shi", "shai", "shao", "shou", "shan", "shen", "shang", "sheng", "shu", "shua", "shuo", "shuai", "shui", "shuan", "shun", "shuang",
  "re", "ri", "rao", "rou", "ran", "ren", "rang", "reng", "rong", "ru", "ruo", "rui", "ruan", "run",
  "za", "ze", "zi", "zai", "zei", "zao", "zou", "zan", "zen", "zang", "zeng", "zong", "zu", "zuo", "zui", "zuan", "zun",
  "ca", "ce", "ci", "cai", "cao", "cou", "can", "cen", "cang", "ceng", "cong", "cu", "cuo", "cui", "cuan", "cun",
  "sa", "se", "si", "sai", "sao", "sou", "san", "sen", "sang", "seng", "song", "su", "suo", "sui", "suan", "sun",
  "ya", "yo", "ye", "yai", "yao", "you", "yan", "yin", "yang", "ying", "yong", "yu", "yue", "yuan", "yun",
  "wa", "wo", "wai", "wei", "wan", "wen", "wang", "weng"
]);
